---
# tasks file base-linux for users

- name: Configurando usuário {{ sysadmin }}
#  become: true
  user: 
    name: "{{ sysadmin }}"
    state: present 
    shell: /bin/bash 
    password: $1$XplcWy1D$DgTZQDOdpr41R8vKYlgLa.
    createhome: yes
    home: /home/{{ sysadmin }}
    groups: wheel
...
