---
# tasks file for users
- name: Instalar sudo para o "{{ ansible_distribution }}" versão "{{ ansible_distribution_major_version }}"
  apt: 
    name: sudo 
    state: installed 
    update_cache: yes
  when: ( ansible_os_family == "Debian" )
  register: result

- name: Instalar sudo para o "{{ ansible_distribution }}" versão "{{ ansible_distribution_major_version }}"
  yum: 
    name: sudo 
    state: installed
  when: ( ansible_os_family == "RedHat" )
  register: result

- name: Define o arquivo de configuracao 
  copy:
    src: etc-sudoers 
    dest: /etc/sudoers 
    owner: root 
    group: root 
    mode: 0440
  when: result is success
...
